 name: pipeline

 on:
  push:
    branches:
        - test
 jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3      

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push 
              uses: docker/build-push-action@v6
              with:
                    file: ./Dockerfile
                    push: true
                    tags: ${{secrets.DOCKERHUB_USERNAME}}/app-cat:latest
    deploy:
        runs-on: ubuntu-latest
        needs: [build-image]
        steps:
            - uses: actions/checkout@v2
            
            - name: Authentification
              uses: 'google-github-actions/auth@v2'
              with:
                    credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

            - name: deploy script file
              shell: 'bash'
              run: |
               gcloud storage cp bash_test.sh gs://deploy-file/frontend-script

            - name: deploy on VMs
              shell: 'bash'
              run: |
                gcloud compute ssh "instance-tp" --zone "us-central1-a" --tunnel-through-iap --project "primeval-mark-378114" --command="cd /home/runner/frontend_app && gcloud storage cp gs://deploy-file/frontend-script/bash_test.sh /home/runner/frontend_app && chmod +x bash_test.sh && export DOCKER_USERNAME='${{secrets.DOCKERHUB_USERNAME}}' && export DOCKER_TOKEN='${{secrets.DOCKERHUB_TOKEN}}' && ./bash_test.sh"
