 name: pipeline
 on:
    push:
        branches: ['maric']
 env:
    APPLICATION_NAME: cat-app
 jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3  

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}} 
            
            - name: build the docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:app-cat-box     
        
    deploy-on-gcp:
        needs: [build-image]
        name: deploy to gcp
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: 'Authentification'
          uses: "google-github-actions/auth@v1"
          with:
            credentials_json: "${{secrets.GCP_SERVICE_ACCOUNT_KEY}}"
        - name: deploy script
          shell: 'bash'
          run: |
            gcloud storage cp bash_test.sh gs://cat-app/    

