 name: pipeline

 on:
  push:
    branches:
        - test
 jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
                   
