 name: pipeline
 on:
    push:
        branches: ['lyne']
 env:
    APPLICATION_NAME: app-cat
 jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout repo
           uses: actions/checkout@v4

         - name: Set Up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Connecter avec Docker Hub
           uses: docker/login-action@v3
           with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}
           
         - name: Build and push
           uses: docker/build-push-action@v3
           with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.APPLICATION_NAME}}:latest

    deploy-on-gcp:
      needs: [build-image]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Authentification sur GCP
          uses: "google-github-actions/auth@v1"
          with:
            credentials_json: "${{secrets.GCP_SERVICE_ACCOUNT_KEY}}"

        - name: Deploy the script
          shell: 'bash'
          run: |
            gcloud storage cp bash_test.sh gs://cat-app/   
      
