 name: Example Pipeline

 on:
    push:
        branches:
            - test-actions
 jobs:
    build-image: 
        runs-on: ubuntu-latest
        
        steps:
         - name: Checkout Repository
           uses: actions/checkout@v2
        
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        
         - name: Build and push
           uses: docker/build-push-action@v6
           with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{secrets.DOCKERHUB_USERNAME}}/app-cat:latest

    deploy-on-gcp:
        needs: [build-image]
        name: deploy to gcp
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v3.5.3
             - name: 'Authentification'
               uses: "google-github-actions/auth@v1"
               with:
                credentials_json: "${{secrets.GCP_SERVICE_ACCOUNT_KEY}}"
    
             - name: deploy file on buckets
               shell: 'bash'
               run: |
                gcloud storage cp bash_test.sh gs://deploy-file/frontend-script