 name: pipeline
 on:
    push:
        branches: ['maric']
 env:
    APPLICATION_NAME: cat-app
 jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
         - name: Set Up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Connecter avec Docker Hub
           uses: docker/login-action@v3
           with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}


